name: Handle Lockfile update
on:
  status:
  check_run:
    types:
      - completed
jobs:
  handleLockfileUpdate:
    runs-on: ubuntu-latest
    if: github.event.action == 'check_run' || github.event.state != 'pending'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: node handle-lock-file-update.js
        env:
          GITHUB_TOKEN: ${{ secrets.GR2M_PAT }}
