name: Test
"on":
  push:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/statuses/{sha}
          owner: gr2m
          repo: silent-lockfile-update
          sha: ${{ github.sha }}
          state: failure
          description: test status
          context: status-test
        env:
          GITHUB_TOKEN: ${{ secrets.GR2M_PAT }}
