name: Update Lockfile
"on":
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch: {}
jobs:
  updateLockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GR2M_PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: git checkout update-lockfile || git checkout -b update-lockfile
      - run: rm -rf package-lock.json node_modules
      - run: npm install
      - run: git status
      - run: >
          git config user.name github-actions

          git config user.email github-actions@github.com

          git add .

          # fail silently

          git commit -m "build(lockfile): update" && git push origin
          update-lockfile || true
