name: Update Lockfile
"on":
  # every day at 4am pacific time
  schedule:
    - cron: "0 12 * * *"

  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: git checkout update-lockfile || git checkout -b update-lockfile
      - run: rm -rf package-lock.json node_modules
      - run: npm install
      - run: git status
      # TODO: check if there is a file change
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          # fail silently
          git commit -m "build(lockfile): update" && git push origin update-lockfile || true
